# Importuojam numpy

In [3]:
import numpy as np

# Pagrindai

In [1]:
pirmas_sarasas=[1,2,3]
print(pirmas_sarasas)

[1, 2, 3]


In [4]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
sarasas=[1,2,3]

sarasas+sarasas

[1, 2, 3, 1, 2, 3]

In [9]:
a=np.array([1,2,3])
a= a+a
print(a)

a=a*3
print(a)

[2 4 6]
[ 6 12 18]


In [13]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(a)
print(a.shape)
print(type(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
<class 'numpy.ndarray'>


In [14]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(a)
print(a.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [15]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

a.size

9

# Gauname informaciją, pakeičiame norimus elementus

In [17]:
a=np.array(
    [
        [1,2,3,4,5,6,7,8],
        [9,10,11,12,13,14,15,16]
    ]
)

print(a.shape)
print(a[0,1])

(2, 8)
2


In [21]:
a=np.array(
    [
        [1,2,3,4,5],
        [6,7,8,9,10],
        [11,12,13,14,15],
        [16,17,18,19,20]
    ]
)

print(a[0,1:4])
print(a[0:2,2:4])
print(a[0::2, 0:10:2])

[2 3 4]
[[3 4]
 [8 9]]
[[ 1  3  5]
 [11 13 15]]


In [22]:
a=np.array(
    [
        [1,2,3,4,5],
        [6,7,8,9,10],
        [11,12,13,14,15],
        [16,17,18,19,20]
    ]
)

a[1,2]=999
print(a)

[[  1   2   3   4   5]
 [  6   7 999   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]


In [23]:
a=np.array(
    [
        [1,2,3,4,5],
        [6,7,8,9,10],
        [11,12,13,14,15],
        [16,17,18,19,20]
    ]
)

a[0:,::2]=10
print(a)

[[10  2 10  4 10]
 [10  7 10  9 10]
 [10 12 10 14 10]
 [10 17 10 19 10]]


In [25]:
a=np.array(
    [
        [1,2,3,4,5],
        [6,7,8,9,10],
        [11,12,13,14,15],
        [16,17,18,19,20]
    ]
)

#vienu metu ideti kelis skaicius

a[0,2:4] = [10,20]
print(a)

[[ 1  2 10 10  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


3d pavyzdys

In [27]:
b=np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(b)
print(b.shape)
print(b.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
3


In [31]:
b=np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(b[1, 1, 0])
print(b[0,1,1])

7
4


In [ ]:
b=np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

In [32]:
b=np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

b[1,0, :] = [10]
print(b)

[[[ 1  2]
  [ 3  4]]

 [[10 10]
  [ 7  8]]]


# Sukuriame skirtingų tipų sąrašus/masyvus

In [33]:
a=np.zeros(10)
a.dtype
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [34]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.zeros((4,2,3)) #4 eilutes 2 nariai 3 reiksmes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [36]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [37]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [38]:
np.random.rand(4,2)

array([[0.91108338, 0.75010848],
       [0.25246151, 0.38910811],
       [0.19887488, 0.43952577],
       [0.69123883, 0.22023685]])

In [39]:
np.random.rand(4,2,3)

array([[[0.03282225, 0.45510569, 0.14094397],
        [0.00727087, 0.28605482, 0.95320762]],

       [[0.04375917, 0.74744459, 0.58446792],
        [0.85302639, 0.23139737, 0.19711359]],

       [[0.36418917, 0.09577404, 0.49011625],
        [0.65127554, 0.99812759, 0.87744749]],

       [[0.24393057, 0.65063438, 0.27825175],
        [0.69261389, 0.00812444, 0.3550711 ]]])

In [40]:
np.random.randint(10, size=(3,3))

array([[5, 1, 3],
       [4, 6, 0],
       [8, 9, 1]], dtype=int32)

# Matematika

In [41]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [43]:
a=np.array([1,2,3,4])
a=a+2
print(a)

[3 4 5 6]


In [44]:
a=np.array([1,2,3,4])
a-2

array([-1,  0,  1,  2])

In [45]:
a=np.array([1,2,3,4])
a*2

array([2, 4, 6, 8])

In [46]:
a=np.array([1,2,3,4])
a/2

array([0.5, 1. , 1.5, 2. ])

In [48]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a+b

array([ 6,  8, 10, 12])

Skaityti daugiau: https://docs.scipy.org/doc/numpy/reference/routines.math.html

# Statistika

In [50]:
a=np.array([1,2,3,4])
np.min(a)
print(np.min(a))

1


In [51]:
a=np.array([[1,2,3,4],[5,6,7,8]])
np.max(a)

np.int64(8)

In [52]:
a=np.array([
    [9,10,5,4],
    [10,2,4,1],
    [5,6,7,7],
    [3,1,15,10]
    ])

np.max(a,axis=0)

array([10, 10, 15, 10])

In [53]:
a=np.array([
    [9,10,5,4],
    [10,2,4,1],
    [5,6,7,7],
    [3,1,15,10]
    ])

np.max(a,axis=1)

array([10, 10,  7, 15])

In [54]:
b = np.array([
    [[1,2], [3,4]],
    [[5,6], [7,8]]
])

np.max(b,axis=2)

array([[2, 4],
       [6, 8]])

In [56]:
b = np.array([
    [[1,2], [3,4]],
    [[5,6], [7,8]]
])

print(np.sum(b))

a=np.array([
    [9,10,5,4],
    [10,2,4,1],
    [5,6,7,7],
    [3,1,15,10]
    ])

np.sum(a, axis=1)

36


array([28, 17, 25, 29])

# Sąrašų/masyvų pertvarkymas

Figūros pakeitimas (reshape)

In [60]:
pradine=np.array([[1,2,3,4], [5,6,7,8]])
pradine.shape
pradine.reshape((8,1))
pradine.reshape((2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Masyvų sujungimas

In [61]:
m1=np.array([1,2,3,4])
m2=np.array([5,6,7,8])

np.vstack([m1,m2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Įvairūs kiti dalykai

## Boolean kaukės (boolean masking) ir pažengęs indeksavimas (advanced indexing)

In [63]:
data=np.array([[1,2,3,4],[5,6,7,8]])
data[data<4]

array([1, 2, 3])

In [64]:
indeksai=[1,2,3]

a=np.array([1,2,3,4,5,6,7,8])

a[indeksai]

array([2, 3, 4])

# Užduotys

-  Sudaryti matricą(4,5) iš atsitiktinių skaičių.
-  Ekrane atspausdinti:
-  Antros eilutės, ketvirto stulpelio elemento reikšmę 
-  Trečią matricos stulpelį
-  Paskutinę matricos eilutę

In [113]:
a=np.random.randint(10, size=(4,5))
print(a)
print(a[1,3])
print(a[:,2])
print(a[-1])


[[7 7 7 0 7]
 [9 4 4 8 9]
 [3 2 6 7 9]
 [3 5 4 7 5]]
8
[7 4 6 4]
[3 5 4 7 5]


Sudaryti matricą, kur eilučių ir stulpelių skaičių programa sukurtų Random principu.<br>
Į ekraną išvesti matricą, eilučių, stulpelių skaičius ir matricos elementų skaičių

In [112]:
from random import randint
a = np.random.randint(randint(1,10), size=(randint(1,10),randint(1,10)))
print(a)
print(a.shape)
print(a.ndim)
print(a.size)

[[4 2 3 5 9 2 5 5]
 [0 7 7 8 0 4 7 1]
 [9 4 4 3 7 6 6 6]]
(3, 8)
2
24
